
cloud-deploy-samples:
	git clone https://github.com/GoogleCloudPlatform/cloud-deploy-samples/

cicd-4-ml:
	git clone https://github.com/gioacchino-martino/cicd-4-ml
# /blob/main/notebooks/simple_model_training.ipynb
