
################################################################################
# Generated by gaic v1.3 on 2024:03:11 15:17
# Do NOT edit or it might get overwritten. Please edit the .gcloudconfig.yaml (and if needed relaunch the script)!
################################################################################

# [BASH]   source '_env_gaic.sh' 
# [DIRENV] layout ricc_gcloud
export PROJECT_ID="rick-and-nardy-demo"
export PROJECT_NUMBER="849075740253"
export GCP_REGION="us-central1"
export GCP_ACCOUNT="ricc@google.com"
export description="This is the demo in /deploy/custom-targets/vertex-ai/quickstart/ for CD on VAI."
export collaborator="inardini@google.com"
export PROD_PROJECT_ID="rick-and-nardy-prod"
export ENDPOINT_ID="quickstart-prod"
export REGION="us-central1"
export DEV_BACKEND_BUCKET="rick-and-nardy-demo-us-central1-tf-dev-backend"
export PROD_BACKEND_BUCKET="rick-and-nardy-demo-us-central1-tf-prod-backend"
export SKAFFOLD_DEFAULT_REPO="us-central1-docker.pkg.dev/rick-and-nardy-demo/skaffoldume"
