
################################################################################
# Generated by gcloud_auto_import_config v1.3 on 2024:03:18 15:03
# Do NOT edit or it might get overwritten. Please edit the .gcloudconfig.yaml (and if needed relaunch the script)!
################################################################################

# from _env_gaic import *
PROJECT_ID = "rick-and-nardy-demo"
PROJECT_NUMBER = "849075740253"
GCP_REGION = "us-central1"
GCP_ACCOUNT = "ricc@google.com"
description = "This is the demo in /deploy/custom-targets/vertex-ai/quickstart/ for CD on VAI."
collaborator = "inardini@google.com"
PROJECT_NUMBER2 = "849075740253"
PROD_PROJECT_ID = "rick-and-nardy-prod"
ENDPOINT_ID = "demo24-prod"
DEV_ENDPOINT_ID = "demo24-dev"
PREPROD_ENDPOINT_ID = "demo24-preprod"
REGION = "us-central1"
TMPDIR = "out-v3/"
VAI_PIPELINE = "vertex-triptych"
CD_DEPLOYABLE_MODEL = "california_reg_model"
CD_DEPLOYABLE_MODEL_ID = "3485927948584747008"
CD_BOSTON_MODEL = "test_model"
PROD_DEMO_ENDPOINT_ID = "demo24-prod"
DEV_DEMO_ENDPOINT_ID = "demo24-dev"
DEV_BACKEND_BUCKET = "rick-and-nardy-demo-us-central1-tf-dev-backend"
PROD_BACKEND_BUCKET = "rick-and-nardy-demo-us-central1-tf-prod-backend"
SKAFFOLD_DEFAULT_REPO = "us-central1-docker.pkg.dev/rick-and-nardy-demo/skaffoldume"
PIPELINE_NAME = "ricc-cal-demo-vpipeline"
BUCKET_URI = "gs://rick-and-nardy-demo-rnn-demo24"
PIPELINE_ROOT = "gs://rick-and-nardy-demo-rnn-demo24/california_pipeline"
MODEL_PATH = "gs://rick-and-nardy-demo-rnn-demo24/california_pipeline/model"
MODEL_NAME = "california_reg_model_ricc"
