
################################################################################
# Generated by gaic v1.3 on 2024:03:12 11:16
# Do NOT edit or it might get overwritten. Please edit the .gcloudconfig.yaml (and if needed relaunch the script)!
################################################################################

# from _env_gaic import *
PROJECT_ID = "rick-and-nardy-demo"
PROJECT_NUMBER = "849075740253"
GCP_REGION = "us-central1"
GCP_ACCOUNT = "ricc@google.com"
description = "This is the demo in /deploy/custom-targets/vertex-ai/quickstart/ for CD on VAI."
collaborator = "inardini@google.com"
PROJECT_NUMBER2 = "849075740253"
PROD_PROJECT_ID = "rick-and-nardy-prod"
ENDPOINT_ID = "quickstart-prod"
DEV_ENDPOINT_ID = "2371068237996621824"
REGION = "us-central1"
TMPDIR = "out/"
VAI_PIPELINE = "vertex-ai-cloud-deploy-pipeline"
DEV_BACKEND_BUCKET = "rick-and-nardy-demo-us-central1-tf-dev-backend"
PROD_BACKEND_BUCKET = "rick-and-nardy-demo-us-central1-tf-prod-backend"
SKAFFOLD_DEFAULT_REPO = "us-central1-docker.pkg.dev/rick-and-nardy-demo/skaffoldume"
PIPELINE_NAME = "california-demo-pipeline"
BUCKET_URI = "gs://rick-and-nardy-demo-rnn-demo24"
PIPELINE_ROOT = "gs://rick-and-nardy-demo-rnn-demo24/california_pipeline"
MODEL_PATH = "gs://rick-and-nardy-demo-rnn-demo24/california_pipeline/model"
MODEL_NAME = "california_reg_model_ricc"
