

########################################################
# This is a sample from gcloud_auto_import_config v1.3
# Code: https://github.com/palladius/sakura/blob/master/bin/auto_import_config.py
########################################################
# Once done you can do: gcloud config configurations activate YOUR_VAVORITE_CONFIG
local_config:
  auto: true
configurations:
  # You probably DONT WANT TO USE default unless you started on GCP yesterday
  verify-evaluate-cloud-metrics:
    gcloud:
      project: rick-and-nardy-demo
      compute/region: us-central1
      compute/zone: us-central1-b
      account: ricc@google.com
    env:
      # No need! It's auto imported for you. You're welcome
      #PROJECT_ID: this is autopopulated from above
      CLOUD_DEPLOY_PROJECT: "rick-and-nardy-demo"
      OTHER_PROJECT: "rick-and-nardy-paljoo"
      OTHER_PROJECT_ORG: "palladius.joonix.net" # (426276118631)
      OTHER_PROJECT_ORG_ID: "426276118631"
      PN: '849075740253'
      # Billed thru Advocacy
      # https://console.cloud.google.com/welcome?project=rick-and-nardy-paljoo

      #GCP_REGION: this is autopopulated from above
      # VERTEX_TRAINING_JOB_NAME: 'train-test-123'
      # REPO_NAME: 'my-awesome-app'
      # # These work! Just make sure you do it in ORDER. (God bless python dicts naivity)
      # BUCKET: "gs://my-unique-${PROJECT_ID}-bucket"
      # IMAGE_URI: "${GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/my_vertex_image:latest"

# ... Now its time to CRL-D
