
################################################################################
# Generated by gcloud_auto_import_config v1.3 on 2024:03:20 11:51
# Do NOT edit or it might get overwritten. Please edit the .gcloudconfig.yaml (and if needed relaunch the script)!
################################################################################

# [BASH]   source '_env_gaic.sh' 
# [DIRENV] layout ricc_gcloud
export PROJECT_ID="rick-and-nardy-demo"
export PROJECT_NUMBER="849075740253"
export GCP_REGION="us-central1"
export GCP_ZONE="us-central1-b"
export GCP_ACCOUNT="ricc@google.com"
export CLOUD_DEPLOY_PROJECT="rick-and-nardy-demo"
export OTHER_PROJECT="rick-and-nardy-paljoo"
export OTHER_PROJECT_ORG="palladius.joonix.net"
export OTHER_PROJECT_ORG_ID="426276118631"
export PN="849075740253"
