
# skaffold config set --global local-cluster true
# skaffold config set --global build-cache true
# skaffold config set default-repo	..
# init:
# 	skaffold config set gcloud.core.project rick-and-nardy-demo


deploy:
	gcloud deploy apply --file=clouddeploy.yaml --region=us-central1 --project=rick-and-nardy-demo
