
################################################################################
# Generated by gaic v1.3 on 2024:03:22 07:26
# Do NOT edit or it might get overwritten. Please edit the .gcloudconfig.yaml (and if needed relaunch the script)!
################################################################################

# [BASH]   source '_env_gaic.sh' 
# [DIRENV] layout ricc_gcloud
export PROJECT_ID="rick-and-nardy-demo"
export GCP_REGION="us-central1"
export GCP_ACCOUNT="ricc@google.com"
export description="This is the demo in /deploy/custom-targets/vertex-ai/quickstart-v2-verify/ for CD on VAI.
Same as /quickstart/ bnut it has deplioyment verification and NO automation.
"
export collaborator="inardini@google.com"
export PROJECT_NUMBER2="849075740253"
export PROD_PROJECT_ID="rick-and-nardy-prod"
export DESCRIPTION="This is the MAIN Demo for Las Vegas 2024 by Riccardo and Ivan.
With deployment verification.

This is the v4.
v1 cant remember.
v2 the first functioning with single target.
v3 Tryptich with 3 CD targets
v4 This one
"
export ENDPOINT_ID="demo24-prod"
export DEV_ENDPOINT_ID="demo24-dev"
export PREPROD_ENDPOINT_ID="demo24-preprod"
export REGION="us-central1"
export TMPDIR="out-v4-verify/"
export VAI_PIPELINE="vertex-demo-verify"
export CD_DEPLOYABLE_MODEL="california_reg_model"
export CD_DEPLOYABLE_MODEL_ID="8413639997114023936"
export CD_BOSTON_MODEL="test_model"
export PROD_DEMO_ENDPOINT_ID="demo24-prod"
export DEV_DEMO_ENDPOINT_ID="demo24-dev"
export DEV_BACKEND_BUCKET="rick-and-nardy-demo-us-central1-tf-dev-backend"
export PROD_BACKEND_BUCKET="rick-and-nardy-demo-us-central1-tf-prod-backend"
export SKAFFOLD_DEFAULT_REPO="us-central1-docker.pkg.dev/rick-and-nardy-demo/skaffoldume"
export PIPELINE_NAME="ricc-cal-demo-vpipeline"
export BUCKET_URI="gs://rick-and-nardy-demo-rnn-demo24"
export PIPELINE_ROOT="gs://rick-and-nardy-demo-rnn-demo24/california_pipeline"
export MODEL_PATH="gs://rick-and-nardy-demo-rnn-demo24/california_pipeline/model"
export MODEL_NAME="california_reg_model"
export DEMO_MODEL_NAME="california_reg_model"
export DEMO_MODEL_ID="2596959603388317696"
