
################################################################################
# Generated by gaic v1.3 on 2024:03:11 11:55
# Do NOT edit or it might get overwritten. Please edit the .gcloudconfig.yaml (and if needed relaunch the script)!
################################################################################

# [BASH]   source '_env_gaic.sh' 
# [DIRENV] layout ricc_gcloud
export PROJECT_ID="rick-and-nardy-demo"
export PROJECT_NUMBER="849075740253"
export GCP_REGION="us-central1"
export GCP_ZONE="us-central1-c"
export GCP_ACCOUNT="ricc@google.com"
export DESCRIPTION="rick-and-nardy-demo is in Gugol org so no public IPs allowed"
export ENDPOINT_ID="quickstart-prod"
